import Head from "next/head";
import Layout from "../../components/Layout/Layout";
import EventCard from "../../components/Events/EventCard/EventCard";
import { fetchAPI, getSortedEventsData } from "../../lib/api";

import classes from "./index.module.scss";

export async function getStaticProps() {
  const [globalData, eventsData] = await Promise.all([
    fetchAPI("/global?populate=deep"),
    getSortedEventsData(),
  ]);
  return {
    props: { globalData, eventsData },
    revalidate: 1,
  };
}

export default function Events({ globalData, eventsData }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout globalData={globalData}>
        <div className={classes.Events}>
          <div className="u-section-heading">
            <h1>Upcoming Events</h1>
            <h4>"Let us consider one another in order to stir up love and good works" Hebrews 10:24</h4>
          </div>
          <div className={classes.Events__cards}>
            {eventsData.map((event) => (
              <EventCard key={event.id} event={event} />
            ))}
          </div>
        </div>
      </Layout>
    </>
  );
}
