import Head from "next/head";
import Layout from "../../components/Layout/Layout";
import { fetchAPI } from "../../lib/api";

import classes from "./index.module.scss";

export async function getStaticProps() {
  const [globalData] = await Promise.all([fetchAPI("/global?populate=deep")]);
  return {
    props: { globalData },
    revalidate: 1,
  };
}

const About = ({ globalData }) => (
  <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Layout globalData={globalData}>
      <main>
        <div className={classes.About}>About Page</div>
      </main>
    </Layout>
  </>
);

export default About;
