import Head from "next/head";
import Image from "next/image";
import Layout from "../components/Layout/Layout";
import { fetchAPI } from "../lib/api";

import styles from "./index.module.scss";

export async function getStaticProps() {
  const [homeData, globalData] = await Promise.all([
    fetchAPI("/home?populate=*"),
    fetchAPI("/global?populate[0]=Navbar.logo&populate[1]=Navbar.links")
  ])
  return {
    props: { homeData, globalData },
    revalidate: 1
  }
}

export default function Home({ homeData, globalData }) {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Layout homeHeaderImage={homeData.data.attributes.headerImage.data.attributes.url} globalData={globalData}>
          <p>
            Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ipsa, ad
            dicta! Nisi, aspernatur hic ipsum magnam ullam quaerat facilis sequi
            quod, illum quia nostrum ipsam quos numquam vero magni quisquam.
          </p>
        </Layout>
      </main>
    </>
  );
}
