import Head from "next/head";
import { getAllJobSlugs, getJobData, fetchAPI } from "../../lib/api";
import Layout from "../../components/Layout/Layout";

export async function getStaticPaths() {
  const paths = await getAllJobSlugs();
  return {
    paths,
    fallback: false,
  };
}

export async function getStaticProps({ params }) {
  const [globalData, jobData] = await Promise.all([
    fetchAPI("/global?populate=deep"),
    getJobData(params.slug),
  ]);

  return {
    props: {
      globalData,
      jobData,
    },
    revalidate: 1,
  };
}

const Job = ({ jobData, globalData }) => (
  <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Layout globalData={globalData}>
      <div className="u-section-heading">
        <div className="row">
          <h1>
            Job Opening:
            <br />
            {jobData.attributes.jobTitle}
          </h1>
        </div>
      </div>
      <div className="row">
        <div className="u-line-width-limited">
          <div
            dangerouslySetInnerHTML={{ __html: jobData.attributes.description }}
          ></div>
        </div>
      </div>
    </Layout>
  </>
);

export default Job;
